name: Trigger pipeline deploy

on:
  push:
    branches: [ "CHK-4016-fix-app-version" ]

  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  semver_labels:
    name: Read semver labels from merged PR
    runs-on: ubuntu-latest
    outputs:
      semver_app: ${{ steps.semver_labels.outputs.semver_app }}
      semver_chart: ${{ steps.semver_labels.outputs.semver_chart }}
      skip_release: ${{ steps.semver_labels.outputs.skip_release }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: 'CHK-4016-fix-app-version'
      - uses: ./.github/actions/check-pr-semver-labels
        id: semver_labels
        with:
          github_token: ${{ secrets.BOT_GITHUB_TOKEN}}
  semver_update:
    name: Update semver for every eligible file of repo (helm charts, gradle files, etc.)
    runs-on: ubuntu-latest
    environment: prod
    outputs:
      app_version: ${{ steps.get_new_ver.outputs.version }}
    steps:
      # Without this step, changes would be applied to a detached head
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: 'CHK-4016-fix-app-version'
      # setup git author
      - name: Setup git author
        run: |
          git config --global user.email "${{ secrets.BOT_GIT_MAIL }}" && git config --global user.name "${{ secrets.BOT_GIT_USER }}"
        # bump version
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Get New App Version
        id: get_new_ver
        run: |
          ./gradlew help incrementVersion --versionIncrementType=${{ steps.semver_labels.outputs.semver_app }} 
          version=$(./gradlew printVersion -Psnapshot=false  -q | head -n1 | cut -d' ' -f2)
          git add build.gradle.kts
          echo $version
          echo "version=$version" >> $GITHUB_OUTPUT
      - name: Update Helm Version Values
        run: |
          for i in helm/values-*.yaml; do
            [ -f "$i" ] || break
            yq -i ".microservice-chart.image.tag = \"${{steps.get_new_ver.outputs.version}}\"" "$i"
            git add "$i"
          done
      - name: Update Chart App Version
        run: |
          CHART_FILE="helm/Chart.yaml"
            if [[ -f "$CHART_FILE" ]]; then
              yq -i ".appVersion = \"${{steps.get_new_ver.outputs.version}}\"" "$CHART_FILE"
              git add "$CHART_FILE"
          fi
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'
      - name: Install semver globally
        run: yarn global add semver
      - name: Update Chart Version
        run: |
          RELEASE_CHART_SEMVER= ${{ steps.semver_labels.outputs.semver_chart }}
          CHART_FILE="helm/Chart.yaml"
          CURRENT_CHART_VERSION=$(yq -r '.version' $CHART_FILE)
          if [[ -f "$CHART_FILE" ]]; then
            yq -i ".version = \"$(semver $CURRENT_CHART_VERSION -i $RELEASE_CHART_SEMVER )\"" "$CHART_FILE"
            git add "$CHART_FILE"
          fi
        # push new version
      - name: Push New Version
        run: |
          git diff --cached
          git commit -m "Bump version [skip ci]"
          git push origin 'CHK-4016-fix-app-version'
  github_release:
    name: Create a New Github Release
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout release branch
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.BOT_GITHUB_TOKEN }}
          ref: 'CHK-4016-fix-app-version'
      - name: Set Up Github Release
        id: setup_github_release
        run: |
          CHART_FILE="helm/Chart.yaml"
          chart_version=$(yq -r '.version' $CHART_FILE)
          HEAD_SHA=$(git rev-parse HEAD)
          TAG="$chart_version"
          TITLE="Release $chart_version"
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_OUTPUT
          echo "TAG=$TAG" >> $GITHUB_OUTPUT
          echo "TITLE=$TITLE" >> $GITHUB_OUTPUT
        # create new github release
      - name: Create New Github Release
        uses: ncipollo/release-action@v1.16.0
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
        with:
          commit: ${{ steps.setup_github_release.outputs.HEAD_SHA }}
          tag: ${{ steps.setup_github_release.outputs.TAG }}
          name: ${{ steps.setup_github_release.outputs.TITLE }}
          makeLatest: true
          generateReleaseNotes: true
          draft: false
          prerelease: false
  azure-devops-deploy-pipeline:
    name: Trigger azure devops deploy pipeline
    runs-on: ubuntu-latest
    needs: semver_labels
    environment: prod
    steps:
      - name: Configure pipeline parameters
        id: configure_pipeline_parameters
        run: |
          echo "ðŸ“ Inputs"
          echo "pull request merged: ${{ github.event.pull_request.merged}}"
          echo "Semver app: ${{ needs.semver_labels.outputs.semver_app}}"
          echo "Semver chart: ${{ needs.semver_labels.outputs.semver_chart}}"
          echo "Skip release: ${{ needs.semver_labels.outputs.skip_release}}"
          semverApp=$(echo ${{ needs.semver_labels.outputs.semver_app}} | sed "s/ignore-for-release/none/")
          semverChart=$(echo ${{ needs.semver_labels.outputs.semver_chart }} |  cut -d'-' -f2 )
          skipRelease=$(echo ${{ needs.semver_labels.outputs.skip_release }})
          echo "DEV_DEPLOY=True" >> $GITHUB_OUTPUT
          echo "UAT_PROD_DEPLOY=True" >> $GITHUB_OUTPUT
          echo "RELEASE_SEMVER=$semverApp" >> $GITHUB_OUTPUT
          echo "RELEASE_CHART_SEMVER=$semverChart" >> $GITHUB_OUTPUT
          echo "FORCE_REPLACE_DOCKER_IMAGE=False" >> $GITHUB_OUTPUT
          echo "SKIP_RELEASE=$skipRelease" >> $GITHUB_OUTPUT
          echo "UAT_SKIP_BLUE_DEPLOYMENT=True" >> $GITHUB_OUTPUT
          echo "PROD_SKIP_BLUE_DEPLOYMENT=True" >> $GITHUB_OUTPUT
          echo "SKIP_BUILD=False" >> $GITHUB_OUTPUT
        shell: bash
      - name: Log pipeline parameters
        run: |
          echo "ðŸª› Pipeline parameters"
          echo "DEV_DEPLOY=${{ steps.configure_pipeline_parameters.outputs.DEV_DEPLOY }}"
          echo "UAT_PROD_DEPLOY=${{ steps.configure_pipeline_parameters.outputs.UAT_PROD_DEPLOY }}"
          echo "RELEASE_SEMVER=${{ steps.configure_pipeline_parameters.outputs.RELEASE_SEMVER }}"
          echo "RELEASE_CHART_SEMVER=${{ steps.configure_pipeline_parameters.outputs.RELEASE_CHART_SEMVER }}"
          echo "FORCE_REPLACE_DOCKER_IMAGE=${{ steps.configure_pipeline_parameters.outputs.FORCE_REPLACE_DOCKER_IMAGE }}"
          echo "SKIP_RELEASE=${{ steps.configure_pipeline_parameters.outputs.SKIP_RELEASE }}"
          echo "UAT_SKIP_BLUE_DEPLOYMENT=${{ steps.configure_pipeline_parameters.outputs.UAT_SKIP_BLUE_DEPLOYMENT }}"
          echo "PROD_SKIP_BLUE_DEPLOYMENT=${{ steps.configure_pipeline_parameters.outputs.PROD_SKIP_BLUE_DEPLOYMENT }}"
          echo "SKIP_BUILD=${{ steps.configure_pipeline_parameters.outputs.SKIP_BUILD }}"
        shell: bash